# Numpy科学计算库

### 目录
* 1.概述
* 2.Array 数组
* 3.数组结构
* 4.数组类型
* 5.数值运算
* 6.排序
* 7.形状的改变
* 8.数组生成
* 9.常用数据生成函数
* 10.四则运算
* 11.随机模块
* 12.文件读取
* 13.数据保存
* 14.练习题

In [1]:
import numpy as np

## 1.概述
* 数组array运算(加减乘除)【位数要一致】

运算

In [2]:
#列表不能加1，但array可以直接计算
a=[1,2,3,4,5]
a+1

TypeError: can only concatenate list (not "int") to list

In [129]:
a=np.array([1,2,3,4,5])
print(a)
print(a+1)

[1 2 3 4 5]
[2 3 4 5 6]


In [130]:
b=a+1
print(b)

[2 3 4 5 6]


In [6]:
# 可以直接相加,但列数必须相同
a+b

array([ 3,  5,  7,  9, 11])

In [131]:
c=np.array([10,2,3,4])
c

array([10,  2,  3,  4])

In [21]:
a+c

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [22]:
a*b

array([ 2,  6, 12, 20, 30])

In [24]:
a-b

array([-1, -1, -1, -1, -1])

In [28]:
a*c

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

切片

In [29]:
a=np.array([1,2,3,4,5])
a[2]

3

In [36]:
np.shape(a)

(5,)

In [34]:
type(a)

numpy.ndarray

In [38]:
#numpy结构
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
#列表结构
a=[[1,2,3],[2,3,4]]
a

[[1, 2, 3], [2, 3, 4]]

## 2.Array 数组
* 数组里要统一数据类型,如果不是会向下进行转换

In [41]:
a_list=[1,2,3,4,5]
a_array=np.array(a_list)
a_array

array([1, 2, 3, 4, 5])

In [42]:
type(a_array)

numpy.ndarray

In [44]:
a_array.dtype

dtype('int32')

In [48]:
a_array.size  ## 数组中的个数

5

In [50]:
a_array.fill(1)
a_array

array([1, 1, 1, 1, 1])

索引和切片

In [52]:
tang_list=[1,2,3,4,5]
tang_array=np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [53]:
tang_array[1:4]

array([2, 3, 4])

In [56]:
tang_list[-2:]

[4, 5]

## 3.数组结构
* 复制用copy()
* 用np.where()来找出索引

矩阵格式（多维的格式）

In [58]:
tang_array=np.array([[1,2,3],
                   [4,3,2],
                   [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 3, 2],
       [7, 8, 9]])

In [59]:
tang_array.shape

(3, 3)

In [60]:
tang_array.size

9

In [61]:
tang_array.ndim   ### 两维

2

In [63]:
tang_array[1,0]

4

In [65]:
tang_array[1,0]=10
tang_array[1,0]

10

In [66]:
tang_array[1]

array([10,  3,  2])

In [70]:
tang_array[:,1]

array([2, 3, 8])

In [71]:
tang_array[1,0:2]

array([10,  3])

In [72]:
tang_array2=tang_array   ### tang_array2 没有存储，只是指向tang_array的位置
tang_array2

array([[ 1,  2,  3],
       [10,  3,  2],
       [ 7,  8,  9]])

In [73]:
tang_array2[1,0]=100
tang_array2

array([[  1,   2,   3],
       [100,   3,   2],
       [  7,   8,   9]])

In [74]:
tang_array

array([[  1,   2,   3],
       [100,   3,   2],
       [  7,   8,   9]])

In [79]:
tang_array2=tang_array.copy()    ### 用COPY来另存储位置
tang_array2

array([[  1,   2,   3],
       [100,   3,   2],
       [  7,   8,   9]])

In [80]:
tang_array2[1,0]=1000
tang_array2

array([[   1,    2,    3],
       [1000,    3,    2],
       [   7,    8,    9]])

In [81]:
tang_array

array([[  1,   2,   3],
       [100,   3,   2],
       [  7,   8,   9]])

构造数组,指定索引

In [82]:
tang_array=np.arange(0,100,10)
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
mask=np.array([0,0,1,1,1,0,0,2,0,3],dtype=bool)
mask   ### 大于0的为True

array([False, False,  True,  True,  True, False, False,  True, False,
        True])

In [86]:
tang_array[mask]   ### 找出为True 的数值

array([20, 30, 40, 70, 90])

用np.random.rand()产生随机的数

In [87]:
random_array=np.random.rand(10)
random_array

array([0.79963686, 0.32764803, 0.38678561, 0.85551175, 0.8967571 ,
       0.57769192, 0.10173624, 0.37135214, 0.41867158, 0.77118944])

In [89]:
mask=random_array>0.5
mask

array([ True, False, False,  True,  True,  True, False, False, False,
        True])

In [90]:
random_array[mask]

array([0.79963686, 0.85551175, 0.8967571 , 0.57769192, 0.77118944])

In [91]:
tang_array[mask]

array([ 0, 30, 40, 50, 90])

In [94]:
tang_array=np.arange(10,60,10)
tang_array

array([10, 20, 30, 40, 50])

In [96]:
tang_array>30     ###返回的布尔型

array([False, False, False,  True,  True])

In [97]:
np.where(tang_array>30)    ### 找出大于30的索引值

(array([3, 4], dtype=int64),)

In [99]:
tang_array[np.where(tang_array>30)]   ### 取出数组中的值

array([40, 50])

In [26]:
tang_array=np.array([[12,22,33],[20,30,40],[45,36,27]])
print(tang_array[tang_array>19])
print(tang_array[np.where(tang_array>19)])

[22 33 20 30 40 45 36 27]
[22 33 20 30 40 45 36 27]


## 4.数据类型
* 类型转换（astype或者asarray，都不会改变原值）

In [100]:
tang_array=np.array([1,2,3,4,5],dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [101]:
tang_array.dtype

dtype('float32')

In [103]:
tang_array.nbytes    #### 占用的多少字节

20

In [8]:
tang_array=np.array([1,2,3,3.5,'str'])     #### 不能直接计算，要转换成 object 类型，如下转换
tang_array

array(['1', '2', '3', '3.5', 'str'], dtype='<U32')

In [10]:
tang_array=np.array([1,2,3,3.5,'str'],dtype=np.object)
tang_array

array([1, 2, 3, 3.5, 'str'], dtype=object)

In [11]:
tang_array*2

array([2, 4, 6, 7.0, 'strstr'], dtype=object)

In [14]:
### asarray 没有改原值
tang_array=np.array([1,2,3,4])
np.asarray(tang_array,dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [16]:
### astype没有修改原值
tang_array=np.array([1,2,3,4])
tang_array.astype(np.float32)

array([1., 2., 3., 4.], dtype=float32)

## 5.数值计算

In [37]:
tang_array=np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.sum(tang_array)

21

指定维度求和

In [38]:
np.sum(tang_array,axis=0)

array([5, 7, 9])

In [19]:
np.sum(tang_array,axis=1)

array([ 6, 15])

In [22]:
np.sum(tang_array,axis=-1)

array([ 6, 15])

In [21]:
tang_array.sum(axis=1)

array([ 6, 15])

求积、最大值、最小值类似

In [23]:
tang_array.prod()

720

In [24]:
tang_array.prod(axis=1)

array([  6, 120])

最大、最小索引

In [27]:
tang_array=np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
tang_array.argmin()

0

In [30]:
tang_array.argmin(axis=0)

array([0, 0, 0], dtype=int64)

平均值和标准差、方差

In [34]:
tang_array.mean(axis=0)

array([2.5, 3.5, 4.5])

In [35]:
tang_array.mean(axis=1)

array([2., 5.])

In [36]:
tang_array.std(axis=1)

array([0.81649658, 0.81649658])

In [38]:
tang_array.var(axis=1)

array([0.66666667, 0.66666667])

数组的限制clip和四舍五入round

In [39]:
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
### 小于2的全变成2，大于4的，全变成4
tang_array.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

In [41]:
### 四舍五入
tang_array=np.array([1.2,2.56,3.7])
tang_array.round()

array([1., 3., 4.])

In [42]:
###强调精度,小数点后两位
tang_array.round(decimals=1)

array([1.2, 2.6, 3.7])

## 2.6 排序
* np.sort(tang_array) 和 tang_array.sort()的区别
* 找出排序的索引值np.argsort()
* 构造平均的数值np.linspace(),找出插入的位置searchsorted
* lexsort混合排序

In [79]:
import numpy as np
tang_array=np.array([[1.5,1.3,1.2],
                    [5.6,7.8,1.9]])

In [81]:
tang_array

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 1.9]])

In [78]:
tang_array.sort()    ### 会改变原数组的值
tang_array

array([[1.2, 1.3, 1.5],
       [1.9, 5.6, 7.8]])

In [80]:
np.sort(tang_array,axis=1)   ### 不会修改原值

array([[1.2, 1.3, 1.5],
       [1.9, 5.6, 7.8]])

In [60]:
np.sort(tang_array,axis=0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 1.2]])

索引值排序

In [84]:
tang_array

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 1.9]])

In [83]:
np.argsort(tang_array)

array([[2, 1, 0],
       [2, 0, 1]], dtype=int64)

构造平均的数值,找出插入的位置

In [85]:
tang_array=np.linspace(0,10,10)   ### 构造0到10，平均的10个数
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [86]:
values=np.array([2.5,6.5,9.6])

In [87]:
np.searchsorted(tang_array,values)   ### 排序好的数组，

array([3, 6, 9], dtype=int64)

lexsort混合排序

In [88]:
tang_array=np.array([[1,0,6],
                     [1,7,0],
                     [2,3,1],
                     [2,4,0]
                    ])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [89]:
index=np.lexsort([-1*tang_array[:,0],tang_array[:,2]])   # 第三列升序，第一列降序
index

array([3, 1, 2, 0], dtype=int64)

In [91]:
tang_array[index]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

## 7.数组形状操作
* shape和reshape的区别
* 添加一个维度 np.newaxis
* 删除空轴tang_arrary.squeeze(),前和后的空值都可以
* 拼接np.contancate()、 vstack()和hstack
* 拉平变成一维数据，a.flatten()和a.raval()

In [93]:
import numpy as np

In [94]:
tang_arrary=np.arange(10)
tang_arrary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
tang_arrary.shape

(10,)

改变形状

In [97]:
### 改变形状
tang_arrary.shape=2,5
tang_arrary

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
tang_arrary.reshape(2,5)
tang_arrary

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
tang_arrary=np.arange(10)
tang_arrary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
tang_arrary.shape   ### 一维的数据

(10,)

压缩空值 squeeze()

In [112]:
tang_arrary=tang_arrary[np.newaxis,:]


In [113]:
tang_arrary.shape    ### 修改成了二维的数据，添加一个轴

(1, 10)

In [114]:
tang_arrary=tang_arrary.squeeze()
tang_arrary.shape

(10,)

In [108]:
tang_arrary=tang_arrary[:,np.newaxis,np.newaxis]
tang_arrary.shape

(10, 1, 1)

In [110]:
tang_arrary=tang_arrary.squeeze()
tang_arrary.shape

(10,)

In [118]:
tang_arrary=np.arange(10)
tang_arrary.shape=2,5
tang_arrary

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
tang_arrary.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

数组的连接

In [132]:
a=np.array([[234,345,567],[34,45,67]])
a

array([[234, 345, 567],
       [ 34,  45,  67]])

In [131]:
b=np.array([[24,35,57],[234,145,267]])
b

array([[ 24,  35,  57],
       [234, 145, 267]])

In [135]:
c=np.concatenate((a,b))   ###默认按行拼接  axis=0
c

array([[234, 345, 567],
       [ 34,  45,  67],
       [ 24,  35,  57],
       [234, 145, 267]])

In [136]:
c=np.concatenate((a,b),axis=0)  
c

array([[234, 345, 567],
       [ 34,  45,  67],
       [ 24,  35,  57],
       [234, 145, 267]])

In [137]:
c=np.concatenate((a,b),axis=1)  
c

array([[234, 345, 567,  24,  35,  57],
       [ 34,  45,  67, 234, 145, 267]])

In [138]:
np.vstack((a,b))

array([[234, 345, 567],
       [ 34,  45,  67],
       [ 24,  35,  57],
       [234, 145, 267]])

In [139]:
np.hstack((a,b))

array([[234, 345, 567,  24,  35,  57],
       [ 34,  45,  67, 234, 145, 267]])

拉平，变成一维a.flatten()

In [140]:
a

array([[234, 345, 567],
       [ 34,  45,  67]])

In [141]:
a.shape

(2, 3)

In [146]:
b=a.flatten()    ### 拉平变成一维
b

array([234, 345, 567,  34,  45,  67])

In [145]:
b.shape

(6,)

In [147]:
a

array([[234, 345, 567],
       [ 34,  45,  67]])

In [151]:
b=a.ravel()

In [152]:
b

array([234, 345, 567,  34,  45,  67])

## 8.数组生成
* np.arange(10)
* np.linspace()
* np.logspace()
* 构造向量 np.r_ 和np.c_

In [153]:
import numpy as np

In [154]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [158]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

In [159]:
np.arange(20,2,-2,dtype=np.float32)

array([20., 18., 16., 14., 12., 10.,  8.,  6.,  4.], dtype=float32)

In [164]:
np.linspace(0,10,50)   ## 从0开始，到10，平均  50个

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

默认10为底

In [167]:
np.logspace(2,10,5)

array([1.e+02, 1.e+04, 1.e+06, 1.e+08, 1.e+10])

In [169]:
## help(np.logspace)

构造向量

In [170]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 9.常用生成函数
* 构造全0或全1的数组 zeros,ones
* 构造np.zeros_like(a) 和np.ones_like 数组，模拟 a 数组
* 构造对角线矩阵全为1  np.identity(5)

In [172]:
np.zeros(3)

array([0., 0., 0.])

In [173]:
np.ones(3)

array([1., 1., 1.])

In [175]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [176]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [177]:
np.ones((3,3)) *8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [179]:
np.ones((3,3),dtype=np.float32) *8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]], dtype=float32)

In [183]:
x=np.empty(6)
x.shape

(6,)

In [186]:
x.fill(1)  ### 修改原值
x

array([1., 1., 1., 1., 1., 1.])

In [190]:
a=x.fill(1)
a

In [191]:
tang_array=np.array([1,2,3,4])
tang_array

array([1, 2, 3, 4])

In [192]:
np.zeros_like(tang_array)

array([0, 0, 0, 0])

In [193]:
np.ones_like(tang_array)

array([1, 1, 1, 1])

np.indentity(n)  n 代表是矩阵的维度

In [195]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 10.四则运算
* 保持维度一致
* 乘积 multiply和 dot（维度交换位置） 的区别
* x * y 维度不一致，会默认转换（不建议此操作）
* 两个数组比较是否一致(每个值要相同)
* 逻辑操作，logical_and和logical_not

In [1]:
import numpy as np

In [3]:
x=np.array([5,5])
y=np.array([2,2])

In [4]:
np.multiply(x,y)

array([10, 10])

In [5]:
np.dot(x,y)

20

In [7]:
x.shape=2,1
y.shape=1,2

In [10]:
print(x)
print(y)

[[5]
 [5]]
[[2 2]]


In [11]:
print(x.shape)
print(y.shape)

(2, 1)
(1, 2)


In [8]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [9]:
np.dot(y,x)

array([[20]])

In [14]:
x=np.array([1,1,1])    ### 默认转换
y=np.array([[1,2,3],[4,5,6]])
print(x*y)

[[1 2 3]
 [4 5 6]]


In [23]:
x=np.array([1,1,1])
y=np.array([1,1,1])

In [27]:
x == y

array([ True,  True,  True])

In [28]:
x=np.array([1,1,1,2])
y=np.array([1,1,1])
print(x==y)

False


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  This is separate from the ipykernel package so we can avoid doing imports until


In [30]:
x=np.array([1,1,1,2])
y=np.array([1,1,1,4])
x==y

array([ True,  True,  True, False])

In [32]:
np.logical_and(x,y)   ###逻辑操作

array([ True,  True,  True,  True])

In [33]:
np.logical_not(x,y) 

array([0, 0, 0, 0])

## 11.随机模块
* 构造随机数组,rand,randint,normal
* 洗牌 np.random.shuffle()
* 随机的种子np.random.seed()

构造三行两列的随机值，所有值都是0到1

In [35]:
np.random.rand(3,2)    

array([[0.87345246, 0.03547199],
       [0.50475089, 0.15752952],
       [0.54765047, 0.72853468]])

构造0到10的随机整数值左开右闭，randint,size确定形状

In [37]:
np.random.randint(10,size=(4,5))

array([[0, 3, 2, 5, 1],
       [9, 5, 6, 2, 8],
       [4, 9, 6, 0, 5],
       [1, 7, 8, 3, 1]])

返回一个0到1的随机值

In [40]:
np.random.rand()

0.996708584733697

0到10取随机3个数

In [42]:
np.random.randint(0,10,3)

array([2, 8, 6])

高斯分布

In [49]:
mu,sigma=0,0.1
np.random.normal(mu,sigma,10)

array([ 0.11077539, -0.08005994,  0.00265624, -0.04973173, -0.17430394,
        0.11695323,  0.10111868,  0.13695423, -0.12618443, -0.01670974])

In [52]:
np.set_printoptions(precision=3)  ### 精确到小数点后几位
mu,sigma=0,0.1
np.random.normal(mu,sigma,10)

array([ 0.185, -0.05 ,  0.045, -0.149,  0.038, -0.119, -0.061,  0.149,
        0.104,  0.004])

洗牌

In [59]:
tang_array=np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.random.shuffle(tang_array)

In [63]:
tang_array

array([4, 2, 6, 5, 0, 1, 3, 8, 7, 9])

随机的种子

In [81]:
np.random.seed(1)
mu,sigma=0,0.1
np.random.normal(mu,sigma,10)

array([ 0.162, -0.061, -0.053, -0.107,  0.087, -0.23 ,  0.174, -0.076,
        0.032, -0.025])

## 12.文件读写
* 自定义函数读取函数（各种情况都可以使用）
* np.loadtxt()：(只有维度一致才可以使用)

In [147]:
%%writefile tang.txt
1 2 3 4 5 6
2 3 4 5 6 7

Overwriting tang.txt


In [148]:
data=[]
with open('tang.txt') as f:
    for line in f.readlines():
        fileds=line.split( )
        cur_data=[float(x) for x in fileds]
        data.append(cur_data)

data=np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

loadtxt()
* skiprows:去掉几行;
* delimiter:分隔符;
* usecols=(0,1,4):指定使用哪几列

In [149]:
data=np.loadtxt('tang.txt')   ### 维度不一致不能用这个，默认的分割符为 ''(空格)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

In [150]:
%%writefile tang2.txt
1,2,3,4,5,6
2,3,4,5,6,7

Writing tang2.txt


In [152]:
data=np.loadtxt('tang2.txt',delimiter=',')
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

In [153]:
%%writefile tang3.txt
x,y,z,w,a,b
1,2,3,4,5,6
2,3,4,5,6,7

Writing tang3.txt


In [155]:
data=np.loadtxt('tang3.txt',delimiter=',',skiprows=1)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.]])

## 13.数据保存
* np.savetxt 保存成TXT文档
* 保存成.npy格式np.save()，读数据np.load()
* 保存多个数组 np.savez(),读数据np.load(),相当于字典格式，用读字典的形式来读取

In [1]:
import numpy as np

In [2]:
tang_array=np.array([[1,2,3],[4,5,6]])

In [3]:
np.savetxt('tang4.txt',tang_array)

* fmt  保存格式
* delimiter 分割符

In [5]:
np.savetxt('tang4.txt',tang_array,fmt='%d',delimiter=',')

存读数据

In [6]:
tang_array=np.array([[1,2,3],[4,5,6]])
np.save('tang_array.npy',tang_array)

In [7]:
tang=np.load('tang_array.npy')
tang

array([[1, 2, 3],
       [4, 5, 6]])

* 存多个数组

In [10]:
tang2=np.arange(10)
tang2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('tang.npz',a=tang,b=tang2)

In [12]:
data=np.load('tang.npz')
data.keys()    ### 相当于字典

['a', 'b']

In [16]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 14.练习题

1.打印当前Numpy的版本号

In [45]:
import numpy as np
np.__version__

'1.14.2'

2.构造全0矩阵， 并打印其占用的内存大小

In [50]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
print('%d bytes' %(z.size*z.itemsize))    ### itemsize 占用内存大小

72 bytes


3.打印一个函数的帮助文档，如numpy.add

In [56]:
## help(np.add)
help(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

4.创建一个10-49的数组，并将其倒序排列

In [59]:
#方法1
np.arange(49,9,-1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [62]:
# 方法二
tang_array=np.arange(10,50,1)
tang_array=tang_array[::-1]
tang_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5.找到一个数组中不为0的索引

In [63]:
np.nonzero([0,1,2,3,4,0,0,123,9,10])

(array([1, 2, 3, 4, 7, 8, 9], dtype=int64),)

6.随机构造3*3的矩阵，并打印其最大和最小值

In [68]:
tang_array=np.random.random((3,3))
tang_array

array([[0.72753098, 0.83994711, 0.41129051],
       [0.66112307, 0.9808326 , 0.246124  ],
       [0.26926211, 0.14403218, 0.25090553]])

In [69]:
np.max(tang_array)

0.9808326015499786

In [70]:
np.min(tang_array)

0.14403217974036508

7.构造一个5*5的矩阵，令其值都为1，并在最外层加上一圈0

In [73]:
tang_array=np.ones((5,5))
tang_array=np.pad(tang_array,pad_width=1,mode='constant',constant_values=0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [100]:
np.random.seed(3)
tang_array=np.random.rand(9)
tang_array.shape=3,3
tang_array

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ]])

In [102]:
tang_array=np.pad(tang_array,pad_width=1,mode='maximum',stat_length=1)  ### mode的最大值
tang_array

array([[0.5507979 , 0.5507979 , 0.70814782, 0.29090474, 0.29090474],
       [0.5507979 , 0.5507979 , 0.70814782, 0.29090474, 0.29090474],
       [0.51082761, 0.51082761, 0.89294695, 0.89629309, 0.89629309],
       [0.12558531, 0.12558531, 0.20724288, 0.0514672 , 0.0514672 ],
       [0.12558531, 0.12558531, 0.20724288, 0.0514672 , 0.0514672 ]])

8.构造一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [104]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

9.对一个5*5的矩阵做归一化操作

In [107]:
tang_array=np.random.random((5,5))
tang_array

array([[0.37799404, 0.09221701, 0.6534109 , 0.55784076, 0.36156476],
       [0.2250545 , 0.40651992, 0.46894025, 0.26923558, 0.29179277],
       [0.4576864 , 0.86053391, 0.5862529 , 0.28348786, 0.27797751],
       [0.45462208, 0.20541034, 0.20137871, 0.51403506, 0.08722937],
       [0.48358553, 0.36217621, 0.70768662, 0.74674622, 0.69109292]])

In [109]:
tang_max=tang_array.max()
tang_min=tang_array.min()
tang_array=(tang_array-tang_min)/(tang_max-tang_min)
tang_array

array([[0.3760028 , 0.00644977, 0.73215855, 0.60857187, 0.35475725],
       [0.17822879, 0.41289108, 0.49361003, 0.23536162, 0.26453149],
       [0.4790571 , 1.        , 0.64531308, 0.25379198, 0.24666626],
       [0.47509446, 0.15282592, 0.1476124 , 0.55192446, 0.        ],
       [0.5125486 , 0.35554795, 0.80234528, 0.85285527, 0.78088711]])

10.找到两个数组中相同的值

In [114]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1,z2))

[9 0 8 4 7 8 5 6 7 3]
[5 1 8 9 2 9 8 9 4 5]
[4 5 8 9]


In [115]:
y=np.datetime64('today','D')-np.timedelta64('1','D')
t=np.datetime64('today','D')
m=np.datetime64('today','D')+np.timedelta64('1','D')
print(y)
print(t)
print(m)

2018-11-18
2018-11-19
2018-11-20


11.得到一个月中的所有的天

In [116]:
np.arange('2019-01','2019-02',dtype='datetime64[D]')

array(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
       '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
       '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
       '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
       '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
       '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
       '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
       '2019-01-29', '2019-01-30', '2019-01-31'], dtype='datetime64[D]')

12.得到一个数的整数部分

In [121]:
z=np.random.normal(0,10,10)
z

array([18.94613926, -0.3101321 , 10.3668147 , 15.02749688, -5.62286734,
        9.09735319, -3.15004065, -5.80901521, -9.70428546,  7.92495087])

In [123]:
np.floor(z)   ### 取出浮点数的整数部分

array([ 18.,  -1.,  10.,  15.,  -6.,   9.,  -4.,  -6., -10.,   7.])

13.构造一个数组，让它不能被改变，不能修改

In [124]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [126]:
z.flags.writeable=False    ### 限定只能读操作
z[0]=1

ValueError: assignment destination is read-only

14.打印大数据量的部分值，全部值

In [130]:
np.set_printoptions(threshold=5)  ## 打印5个
z=np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [129]:
np.set_printoptions(threshold=np.nan)   #  np.nan打印全部
z=np.zeros((15,15))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

15.找到一个数组中，最接近一个数的索引

In [131]:
np.random.seed(123)
z=np.arange(100)
v=np.random.uniform(0,100)
print(v)
index=(abs(z-v).argmin())
print(z[index])

69.64691855978616
70


16.32位的float类型和32位的int类型转换

In [133]:
z=np.arange(100,dtype=np.int32)
print(z.dtype)
z=z.astype(np.float32)
print(z.dtype)

int32
float32


17.打印数组元素位置坐标和数值

In [135]:
z=np.arange(9).reshape(3,3)
for index,values in np.ndenumerate(z):
    print(index,values)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


18.按照数组的某一列进行排序

In [150]:
np.random.seed(234)
z=np.random.randint(0,100,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[72 31 68]
 [57 95 33]
 [ 3 54 63]]
[[72 31 68]
 [ 3 54 63]
 [57 95 33]]


19.统计数组中每个数值出现的次数

In [169]:
np.set_printoptions(threshold=np.nan)
z=np.random.randint(0,5,(10))
print(z)
print(np.bincount(z))

[3 0 1 0 4 2 0 0 2 2]
[4 1 3 1 1]


20.如何对一个四维数组的最后两维进行求和

In [180]:
z=np.random.randint(0,10,(3,3,3,3))
#print(z)
res=z.sum(axis=(-2,-1))
print(res)

[[47 48 24]
 [47 28 41]
 [30 40 38]]


21.交换矩阵中的两行

In [194]:
z=np.arange(25).reshape(5,5)
print(z)
print(z[[0,1]])
z[[0,1]]=z[[1,0]]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


22.找到数组中常出现的数字

In [199]:
z=np.random.randint(0,100,10)
print(z)
print(np.bincount(z))
print(np.bincount(z).argmax())

[78 17 49 17 52  4 31 49 25 61]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1]
17


In [203]:
#help(np.argmax)

23.快速查找TOP K

In [206]:
z=np.arange(10000)
np.random.shuffle(z)
n=5
print(z[np.argpartition(-z,n)[:n]])

[9997 9999 9998 9996 9995]


24.去掉一个数组中，所有元素都相同的数据

In [214]:
z=np.random.randint(0,3,(10,3))
print(z)
e=np.all(z[:,1:]==z[:,:-1],axis=1)
e

[[1 1 1]
 [0 2 1]
 [2 1 1]
 [1 0 2]
 [1 0 0]
 [0 2 1]
 [1 2 1]
 [2 2 2]
 [2 2 2]
 [2 0 0]]


array([ True, False, False, False, False, False, False,  True,  True,
       False])

In [215]:
z[e]

array([[1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])